#!/bin/bash

#Use pandoc to create html page from markdown
pandoc wtbd.md \
--standalone \
--smart \
--css pandoc.css \
--output index.html

#DOCX conversion from markdown
pandoc index.html \
--standalone \
--smart \
--css pandoc.css \
--output wtbd.docx 

#Commit changes and push them to github
#git add --all
#git commit -m "newest update"
#git push

#Update gh-pages to match master branch
#git checkout gh-pages
#git rebase master
#git push origin gh-pages
#git checkout master
